version: '3'
services:
  # Servicio para la API en Node.js
  api:
    build: .
    container_name: node_api
    ports:
      - "3000:3000"
    environment:
      - MYSQL_URI=mysql://root:password@mysql:3306/mydb
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  # Servicio para la base de datos MySQL
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

# Definición de la red
networks:
  app-network:
    driver: bridge

# Volúmenes
volumes:
  mysql-data:

